# Decision tree
## https://www.youtube.com/watch?v=RmajweUFKvM

In [ ]:
## the idea is to divide the dataset and pick a root node and perform decision based on value 
## the root node is taking based on Information gain G which is calculated using Entropy
## entropy is sum of the probablity of earch targer * log base 2(probablity of each target)
## this all calcualtion of entropy is done by the algorithm so need to know for now


In [8]:
import pandas as pd
import numpy as np 
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris
from sklearn.tree import export_graphviz

In [2]:
data = pd.read_csv("Diabetes.csv",header=0)
data.rename(columns={' Number of times pregnant':'Number of times pregnant', ' Plasma glucose concentration':'Plasma glucose concentration',
       ' Diastolic blood pressure':'Diastolic blood pressure', ' Triceps skin fold thickness':'Triceps skin fold thickness',
       ' 2-Hour serum insulin':'2-Hour serum insulin', ' Body mass index':'Body mass index',
       ' Diabetes pedigree function':'Diabetes pedigree function', ' Age (years)':'Age', ' Class variable':'Class variable'},inplace=True)



In [3]:
data.head()

Number of times pregnant  Plasma glucose concentration  \
0                         6                           148   
1                         1                            85   
2                         8                           183   
3                         1                            89   
4                         0                           137   

   Diastolic blood pressure  Triceps skin fold thickness  \
0                        72                           35   
1                        66                           29   
2                        64                            0   
3                        66                           23   
4                        40                           35   

   2-Hour serum insulin  Body mass index  Diabetes pedigree function  Age  \
0                     0             33.6                       0.627   50   
1                     0             26.6                       0.351   31   
2                     0             23.3                       0.672   32   
3                    94             28.1                       0.167   21   
4                   168             43.1                       2.288   33   

  Class variable  
0            YES  
1             NO  
2            YES  
3             NO  
4            YES

In [4]:
data
##%matplotlib inline 
# pyplot.plot(data['Class variable'],data['Number of times pregnant'])
# pyplot.show()
data['Target'] = data['Class variable'].map({'YES':1,'NO':0})
data.drop('Class variable',axis=1,inplace=True)
##pyplot.hist(data['Target'])
## select all the columns except one 
X=data.loc[:,data.columns!='Target']
Y = data['Target']
X_train,X_test,Y_Train,Y_test = train_test_split(X,Y,test_size=0.3,random_state=2)
mdoel = RandomForestClassifier()
mdoel.fit(X_train,Y_Train)
y_pred = mdoel.predict(X_test)
accuracy = metrics.accuracy_score(Y_test,y_pred)
print(accuracy)

0.7792207792207793


In [21]:
data['class'] = data['Target'].map({0:'NO',1:'YES'})

In [6]:
estimator_first = mdoel.estimators_[0]

In [35]:
export_graphviz(estimator_first, out_file='tree.dot', 
                feature_names = X.columns,
                class_names = data['class'],
               rounded = True, proportion = False, 
                precision = 2, filled = True)
from subprocess import call
call(['dot', '-Tpng', 'tree.dot', '-o', 'tree.png', '-Gdpi=600'])

In [32]:
import os
os.getcwd()

'C:\\Users\\kumrajni\\AppData\\Local\\Continuum\\anaconda3\\Scripts\\Jupyter_Learnign\\Jupyter_Learnign'

In [29]:
from subprocess import call
call(['dot', '-Tpng', 'tree.dot', '-o', 'tree.png', '-Gdpi=600'])

FileNotFoundError: [WinError 2] The system cannot find the file specified

In [ ]:
call

In [28]:
from IPython.display import Image
Image(filename = 'tree.png')

FileNotFoundError: [Errno 2] No such file or directory: 'tree.png'

In [ ]:
## implementing first with criterian as "entropy"
## Decision tree has two criterian "entropy" and "gini"
##also there are many parameter value in DecisionTreeClassifier that we should keep in mind
## like min_test_samole ,split_......

In [5]:
## decis_tree = DecisionTreeClassifier(criterion='entropy') ##==  accuracy comes as 66.23% with default paramter 
## decis_tree = DecisionTreeClassifier(criterion='entropy',random_state=200) ## accuracy 67.09
##decis_tree = DecisionTreeClassifier(criterion='entropy',min_samples_split=30) ## 71.4
decis_tree = DecisionTreeClassifier(criterion='gini',min_samples_split=90) ## 74.4



In [6]:
##X = data[[]]
data.columns
X=data[['Number of times pregnant', 'Plasma glucose concentration',
       'Diastolic blood pressure', 'Triceps skin fold thickness',
       '2-Hour serum insulin', 'Body mass index', 'Diabetes pedigree function',
       'Age']]
y = data['Class variable']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=2)

In [7]:
decis_tree.fit(X_train,y_train)
y_pred = decis_tree.predict(X_test)
score = metrics.accuracy_score(y_test,y_pred)
print(score)


0.744588744589


# Random forest

# random forest 
random forest is the collection of many decision tree 
for example to identify IRIS_DATA we take the sepal width in one tree and start building nodes based on sepal width
in another tree we take sepal_length in one tree and start building tree based on sepal length
in another tree we take petal length and start building node based on petal length
# so now we have three tress
and when any input we want to predict  goes to all these 3 trees and result given is based on the majority 
suppost 2 tress decided its setosa and 1 tree decided its virginica then the prediction would be setosa
### https://www.youtube.com/watch?v=GofidHdilas
### https://www.youtube.com/watch?v=eM4uJ6XGnSM

# parameter tuning in random forest
 ##### a:- parameter to make model better(accuracy)
           # n_estimators:- it is the number of trees in the forest, more number of trees better result (but costly on processr)
           # max_features:- it is the number of features we want to take from the available feature(variable) like 
                              max_features=(auto,sqrt,0.9)  suppost 100 we have auto/none will take 100, sqrt:-10.....
           # min_sample_leaf:- it is the minimum number of sample we want to have in the leaf node
                               by default random forest keeps on splitting untill it reaches to one leaf node
                               but when we want to stop the algorithm before 1 sample in leaf node we need to 
                               specify this parameter

## random forest will work on any kind of target(numerical and integers)
### object detection(is it a car, motorbike, bus, building..), kinect gaming console which part of your body is ding what, satellite imaging sension and terrain detection 

In [10]:
## diabitic data
X_ran_for = X
y_ran_for = y
X_train_rand_for,X_test_rand_for,y_train_rand_for,y_test_rand_for = train_test_split(X_ran_for,y_ran_for,test_size=0.3,random_state=2)


In [62]:
rand_forest_clf = RandomForestClassifier(n_jobs=2,random_state=3)
rand_forest_clf.fit(X_train_rand_for,y_train_rand_for)
y_rand_for_pred = rand_forest_clf.predict(X_test_rand_for)
print(metrics.accuracy_score(y_test_rand_for,y_rand_for_pred))

0.744588744589


In [64]:
y_rand_for_pred

array(['NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'YES', 'NO', 'YES', 'NO',
       'NO', 'YES', 'NO', 'NO', 'YES', 'YES', 'NO', 'NO', 'YES', 'YES',
       'YES', 'NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO',
       'NO', 'NO', 'YES', 'YES', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO',
       'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'YES', 'NO',
       'YES', 'YES', 'YES', 'NO', 'NO', 'NO', 'NO', 'YES', 'YES', 'YES',
       'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO',
       'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES', 'YES',
       'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES', 'NO',
       'NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'YES', 'NO',
       'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO',
       'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO',
       'YES', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES', 'NO',
       'NO', 'NO', 'NO', 'NO',

# Random forest on iris data

In [10]:
# iris data 
data_iris = load_iris()
data_iris.feature_names
data_iris.target_names
X_iris_rand = data_iris.data
y_iris_rand = data_iris.target
print(data_iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [11]:
data_iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [4]:

dataframe = pd.DataFrame(data_iris.data)

dataframe.rename(columns={0:'sepal length',1:'sepal width',2:'petal length',3:'petal width'},inplace=True)
dataframe['target1'] = data_iris.target
dataframe['target'] = dataframe['target1'].map({0:'setosa',1:'versicolor',2:'virginica'})
dataframe.drop('target1',axis=1,inplace=True)

In [5]:
X_r = dataframe[['sepal length','sepal width','petal length','petal width']]
y_r = dataframe['target']
Xtrain_,Xtest_,y_train_,y_test_ = train_test_split(X_r,y_r,test_size=0.3,random_state=2)

In [7]:
randm_ = RandomForestClassifier(n_jobs=2,random_state=3)
randm_.fit(Xtrain_,y_train_)
y_pre_ = randm_.predict(Xtest_)
metrics.accuracy_score(y_test_,y_pre_)


0.97777777777777775

#### whenever we want to pass some set of features and want to predict its outcome and we get error like 
### object is not subscriptable pass that as data frame ([['variable']])


In [21]:
randm_.predict([[2,3,4,5]])


array(['virginica'], dtype=object)

In [19]:
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
import pandas as pd
from matplotlib import pyplot
from sklearn.cross_validation import train_test_split
from sklearn.linear_model import LogisticRegression

In [7]:
iris = load_iris()
data = iris.data
target = iris.target

In [12]:
X_train,X_test,Y_train,Y_test = train_test_split(data,target,test_size=0.3,random_state=1)

In [24]:
rand = RandomForestClassifier(n_jobs=2,n_estimators=20)
rand.fit(X_train,Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=2,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [25]:
y_pred = rand.predict(X_test)

In [26]:
accuracy = metrics.accuracy_score(Y_test,y_pred)
accuracy

0.9555555555555556

In [17]:
metrics.confusion_matrix(Y_test,y_pred)

array([[14,  0,  0],
       [ 0, 17,  1],
       [ 0,  1, 12]], dtype=int64)

In [20]:
## using logistic regres
logit = LogisticRegression()
logit.fit(X_train,Y_train)
pred_l = logit.predict(X_test)
print(metrics.accuracy_score(Y_test,pred_l))

0.888888888889
